export const State = {
	debug: false,
	intro: true,
	rules: false,
	game: false,
	paused: true,
	ended: false,
	won: false,
	lost: false,
	keys: {},
	minNeededScore: 75,
	score: 0,
	area: 0,
	minEnemies: 2,
	maxEnemies: 6,
	addEnemy: () => {},
	removeEnemy: () => {},
	addScore: () => {},
	addEnemyScore: () => {},
	onPlayerCut: () => {},
	onPlayerReset: () => {},
};
